"""empty message

Revision ID: 22def7a9b24d
Revises: 6171c4caa71f
Create Date: 2023-07-24 19:17:53.722134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22def7a9b24d'
down_revision = '6171c4caa71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
